**LESSON 2.1**

### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

A.

In [ ]:
import numpy as np

nested_list = [[i for i in range(1, 10)] for i in range(9)] #I created a nested Python list with values from 1 to 9

A = np.array(nested_list) #Converted the nested list into an ndarray object

#1. Using a property of the ndarray object
print("Shape of A:", A.shape) #A.shape returns a tuple with each index having the number of corresponding elements. It indicates that A has 9 rows and 9 columns.

#2. Using a method of the ndarray object
max_value = A.max() #A.max() is a method that returns the maximum value in the ndarray A.
print("Maximum value in A:", max_value)  # To display the maximum number which is 9.

#3. Using a numpy function and passing an ndarray
min_value = np.min(A) #np.min(A) is a numpy function that returns the minimum value in the ndarray A.
print("Minimum value in A:", min_value) #To display the minimum number which is 1.



Shape of A: (9, 9)
Maximum value in A: 9
Minimum value in A: 1


B.

In [ ]:
import numpy as np

ones_array = np.ones((5, 5), dtype=int) # I created a 5x5 integer array filled with ones.

print("Shape of the array:", ones_array.shape) #The shape property of the array returns a tuple representing the dimensions of the array. It's (5, 5) indicating the array has 5 rows and 5 columns.

print("Size of the array:", ones_array.size) #The size property of the array returns the total number of elements in the array. For a 5x5 array, it will be 5*5 = 25.

print("Number of dimensions:", ones_array.ndim) #The ndim property of the array returns the number of dimensions (axes) of the array. It displays 2.


Shape of the array: (5, 5)
Size of the array: 25
Number of dimensions: 2


In [ ]:
import numpy as np

original_array = np.arange(-5, 6) # I created an array of values from -5 to +5.

resulting_array = original_array * 2 # This line of code multiply each value by 2.

print("Resulting array:", resulting_array) # Print the resulting array.


Resulting array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


 **LESSON 2.2**

### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [ ]:
import numpy as np

# This line of code is an array with 30 values within the range of numbers 1 to 100, incrementing by 2. This generates an array starting from 10 up to 70 with a step size of 2.
array_30_values = np.arange(10, 70, 2)

#Displaying the resulting array
print("Array with 30 values within the range of numbers 1 to 100, incrementing by 2:")
print(array_30_values)


Array with 30 values within the range of numbers 1 to 100, incrementing by 2:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [ ]:
import numpy as np

# I created a four-dimensional array of random integers in the interval [0, 12].
four_dim_array = np.random.randint(0, 13, size=(3, 4, 2, 5))

# Print dimensions, shape, and size of the array
print("Dimensions of the array:", four_dim_array.ndim)
print("Shape of the array:", four_dim_array.shape)
print("Size of the array:", four_dim_array.size)

Dimensions of the array: 4
Shape of the array: (3, 4, 2, 5)
Size of the array: 120


In [ ]:
# Getting the maximum number for each dimension and display the maximum number which is 12.
max_per_dimension = np.amax(four_dim_array, axis=(0, 1, 2, 3))
print("Maximum number for each dimension:", max_per_dimension)

Maximum number for each dimension: 12


In [ ]:
# Multiplied each array element by 4 resulting in a new array where each value is four times the original value.
multiplied_array = four_dim_array * 4
print(multiplied_array)

[[[[44  8 24 48 24]
   [28 12 40  0 12]]

  [[44 48 36 40 32]
   [ 4 44  0 32 32]]

  [[24  0 32 48  0]
   [44  4 20 28  8]]

  [[ 8  8 28 12 28]
   [44 16 48  8  4]]]


 [[[ 4  0  4 48  8]
   [32 12  0 48 12]]

  [[ 4 48 32  0 24]
   [48 44 24 28 48]]

  [[32 20 12  4 16]
   [24 24 20 48  8]]

  [[16 36  4  4 44]
   [28 20 44 24 28]]]


 [[[32 44 44 24 24]
   [24 24  8 28 44]]

  [[ 0 36 28 40 12]
   [44 44 32 32 48]]

  [[48  8 24 24 48]
   [ 4 48  4 44 20]]

  [[40 48 16 12 12]
   [20 32 20 24 24]]]]
